apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: 24.2.0  # This matches Bitnami versioning
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    airflow:
      executor: LocalExecutor
    postgresql:
      enabled: true
    redis:
      enabled: true
    defaultAirflowRepository: apache/airflow
    defaultAirflowTag: 2.9.1
